"""Forty short article titles in five topics, for the chapter's lab."""

CORPUS = {
    "cooking": [
        "Roman supplì: fried rice with melting mozzarella",
        "Pasta alla Norma: fried eggplant, tomato and salted ricotta",
        "Granita and brioche, the summer breakfast of Catania",
        "Sicilian cassata, a cake of ricotta and marzipan",
        "How to make Sicilian arancini with ragù and peas",
        "Sicilian cannoli and the secret of the crisp shell",
        "Risotto alla milanese with saffron",
        "Neapolitan pizza: hydration, fermentation and a very hot oven",
    ],
    "volcanoes": [
        "The Aeolian Islands, born of fire from the depths",
        "Earthquakes and magma: how to read an imminent eruption",
        "How an active volcano is monitored with seismographs",
        "Hiking to the summit craters with a mountain guide",
        "Etna's lava flows and the villages they threatened",
        "Ash clouds and flights: when a volcano closes an airport",
        "Pompeii, the city buried by Vesuvius",
        "Why volcanic soil makes such good wine",
    ],
    "computing": [
        "Python 3.14 and the free-threaded interpreter",
        "How a database index speeds up queries",
        "Containers explained: images, layers and registries",
        "Why you should write a test before fixing a bug",
        "Git branches and the art of the small commit",
        "Public-key cryptography in plain words",
        "How a web browser renders a page",
        "Garbage collection: how languages free memory",
    ],
    "sport": [
        "The Catania derby: tactics and tension",
        "Marathon training: the first twelve weeks",
        "How the offside rule really works",
        "Tennis serves: why the ball toss matters",
        "The great climbs of the Giro d'Italia",
        "Swimming technique: breathing every three strokes",
        "Why basketball teams love the three-pointer",
        "Volleyball rotation rules, explained",
    ],
    "economy": [
        "Oil prices rise and weigh on the cost of petrol",
        "Inflation is falling: what changes for variable-rate mortgages",
        "What ETFs are and why small savers buy them",
        "How central banks set interest rates",
        "The Milan stock exchange closes higher on bank shares",
        "Understanding your payslip: gross, net and taxes",
        "Why the euro exchange rate moves",
        "Tourism and the Sicilian economy",
    ],
}
