# Generated by Django 6.1.2 on 2026-10-09 12:07

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sentences", "0001_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300, unique=True)),
                ("topic", models.CharField(max_length=40)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["topic", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SamplePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.PositiveSmallIntegerField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="samplepoint_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
