# Generated by Django 6.1.2 on 2026-10-09 12:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.uuid
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge", "0001_vector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=200, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("hash", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.uuid.UUID7(),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("section", models.CharField(blank=True, max_length=200)),
                ("text", models.TextField()),
                (
                    "search",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector(
                                "section", config="english", weight="B"
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "text", config="english", weight="A"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        related_name="chunks",
                        to="knowledge.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "position"],
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search"], name="chunk_search_gin"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="chunk_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "position"), name="chunk_unique_position"
                    )
                ],
            },
        ),
    ]
