from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.db import models
from django.db.models.functions import UUID7
from pgvector.django import HnswIndex, VectorField


class Document(models.Model):
    # The id is generated by PostgreSQL (UUIDv7: sortable by time, compact index).
    id = models.UUIDField(primary_key=True, db_default=UUID7(), editable=False)
    path = models.CharField(max_length=200, unique=True)
    title = models.CharField(max_length=200)
    # Hash of the content: it tells us whether a document changed since the last import.
    hash = models.CharField(max_length=64)
    imported_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["title"]

    def __str__(self) -> str:
        return self.title


class Chunk(models.Model):
    id = models.UUIDField(primary_key=True, db_default=UUID7(), editable=False)
    document = models.ForeignKey(
        Document, on_delete=models.DB_CASCADE, related_name="chunks"
    )
    position = models.PositiveSmallIntegerField()
    section = models.CharField(max_length=200, blank=True)
    text = models.TextField()

    # A column computed by the database: we never write it, it can't get out of sync.
    search = models.GeneratedField(
        expression=(
            SearchVector("section", weight="B", config="english")
            + SearchVector("text", weight="A", config="english")
        ),
        output_field=SearchVectorField(),
        db_persist=True,
    )

    embedding = VectorField(dimensions=settings.EMBEDDING_DIMENSIONS, null=True, blank=True)
    # Which model produced the vector: it tells us what to regenerate when the model changes.
    model = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ["document", "position"]
        constraints = [
            models.UniqueConstraint(
                fields=["document", "position"], name="chunk_unique_position"
            )
        ]
        indexes = [
            GinIndex(fields=["search"], name="chunk_search_gin"),
            HnswIndex(
                name="chunk_embedding_hnsw",
                fields=["embedding"],
                m=16,
                ef_construction=64,
                opclasses=["vector_cosine_ops"],
            ),
        ]

    def __str__(self) -> str:
        return f"{self.document.title} · {self.section or '—'} #{self.position}"
