# Generated by Django 6.1.2 on 2026-10-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_text_into_first_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="text",
        ),
    ]
