"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP

from . import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Fail closed: if nobody says "development", this is production.
DEBUG = env.boolean("DEBUG", False)

if DEBUG:
    SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-for-development-only")
    ALLOWED_HOSTS = env.comma_list("ALLOWED_HOSTS", ["localhost", "127.0.0.1"])
else:
    SECRET_KEY = env.required("SECRET_KEY")
    ALLOWED_HOSTS = env.comma_list("ALLOWED_HOSTS")
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("ALLOWED_HOSTS is missing: in production it is required.")
CSRF_TRUSTED_ORIGINS = env.comma_list("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # needed for the HNSW index
    "documents",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves the static files in production; in development runserver does it.
    *([] if DEBUG else ["whitenoise.middleware.WhiteNoiseMiddleware"]),
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.csp",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "vault"),
        "USER": os.environ.get("DB_USER", "vault"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "vault") if DEBUG else env.required("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,  # a worker reuses its connection for a minute
        "CONN_HEALTH_CHECKS": True,  # ...after checking that it is still alive
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(os.environ.get("STATIC_ROOT", BASE_DIR / "staticfiles"))
if not DEBUG:
    # Every file gets a fingerprint in its name (vault.a048c2bad75c.css) and can be cached forever.
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }


# Email: in development, printed to the console; in production, an SMTP server is required.
if DEBUG:
    MAILERS = {"default": {"BACKEND": "django.core.mail.backends.console.EmailBackend"}}
else:
    MAILERS = {
        "default": {
            "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
            "OPTIONS": {
                "host": env.required("SMTP_HOST"),
                "port": env.integer("SMTP_PORT", 587),
                "username": os.environ.get("SMTP_USER", ""),
                "password": os.environ.get("SMTP_PASSWORD", ""),
                "use_tls": env.boolean("SMTP_TLS", True),
                "timeout": 10,  # a slow mail server must not hold a request for ever
            },
        },
    }


# --- DjangoVault ---------------------------------------------------------------------------

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "list"

# Uploaded files live here. There is deliberately NO MEDIA_URL: no URL serves this folder;
# files are downloaded through a view that checks permissions.
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / "media"))
MAX_FILE_SIZE = 1_000_000  # bytes
MAX_REVIEWERS = 6

# Background tasks: in this chapter they run right away, in the same process.
TASKS = {"default": {"BACKEND": "django.tasks.backends.immediate.ImmediateBackend"}}

VAULT_FROM = os.environ.get("VAULT_FROM", "vault@example.test")

# "fastembed" is the real model (768 dimensions); "fake" is a bag of words, for tests.
EMBEDDING_BACKEND = os.environ.get("EMBEDDING_BACKEND", "fastembed")
EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
EMBEDDING_DIMENSIONS = 768
EMBEDDING_CACHE = os.environ.get("EMBEDDING_CACHE", str(BASE_DIR / ".embedding-cache"))
RAG_MAX_DISTANCE = 0.6

SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF, CSP.NONCE],
    "style-src": [CSP.SELF],
    "img-src": [CSP.SELF, "data:"],
    "connect-src": [CSP.SELF],
    "object-src": [CSP.NONE],
    "base-uri": [CSP.SELF],
    "form-action": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
}
STATICFILES_DIRS = [BASE_DIR / "static"]


# --- Production ----------------------------------------------------------------------------------------
# The proxy (Caddy) terminates TLS and writes X-Forwarded-Proto. That header can be trusted ONLY if the
# proxy always overwrites it and the application server can't be reached except through the proxy.
if env.boolean("TRUST_PROXY_SSL", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = env.boolean("SECURE_SSL_REDIRECT", True)
    SECURE_REDIRECT_EXEMPT = [r"^health/$", r"^ready/$"]  # the internal checks arrive over HTTP
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS: start small (one hour) and raise it when you are sure; a mistake lasts as long as the value.
    SECURE_HSTS_SECONDS = env.integer("SECURE_HSTS_SECONDS", 3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.boolean("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
    SECURE_HSTS_PRELOAD = False
    SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]  # deliberate choices, explained in the chapter
