# Generated by Django 6.1.2 on 2026-10-09 11:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="search",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.SearchVector(
                            "title", config="english", weight="A"
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "summary", config="english", weight="B"
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "body", config="english", weight="C"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"], name="articles_ar_search_40f7a9_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="articles_ar_tags_737e6f_gin"
            ),
        ),
    ]
