# Generated by Django 6.1.2 on 2026-10-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
    ]
